#
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: blueprints.cloud.google.com/v1alpha1
kind: TerraformBlueprint
metadata:
  name: terraform-google-iam-connector
  source:
    type: git
    git:
      repo: https://github.com/GoogleCloudPlatform/terraform-google-iam
      directory: modules/iam_binding
  version: 1.0.0
  actuationTool:
    type: Terraform
    versions:
      - ">= 1.3"
  title: IAM Connector Module
  description:
    tagline: A generic module for managing IAM bindings on various Google Cloud resources.
    detailed: This module provides a generic interface for creating IAM bindings on various Google Cloud resources. It supports authoritative (`iam_binding`) and additive (`iam_member`) modes, as well as conditional bindings. This module helps enforce the principle of least privilege by allowing granular control over permissions.
  labels:
    gcp: ""
    iam: ""
    security: ""
  examples:
    - name: simple_example
      location:
        type: git
        git:
          repo: https://github.com/GoogleCloudPlatform/terraform-google-iam
          directory: examples/simple_project_iam
          ref: main
  documentations:
    - title: IAM Connector Module
      url: https://github.com/GoogleCloudPlatform/terraform-google-iam/tree/main/modules/iam_binding/README.md
spec:
  terraformVariables:
    - name: bindings
      description: "A map of IAM bindings to apply. The key is the role, and the value is an object containing a list of members and an optional condition. Example `{'roles/storage.objectViewer' = { members = ['user:foo@example.com'], condition = { title = 'expires_2024', expression = 'request.time < timestamp(\"2025-01-01T00:00:00Z\")' } } }`"
      type: map(object({ members = list(string), condition = optional(object({ title = string, description = optional(string), expression = string })) }))
      required: false
      default: {}
    - name: bucket_name
      description: The name of the GCS bucket to apply IAM policies to. Only one of `project_id`, `folder_id`, `organization_id`, `bucket_name`, `service_account_email`, or `pubsub_topic_id` must be specified.
      type: string
      required: false
      default: null
    - name: folder_id
      description: The ID of the folder to apply IAM policies to. Can be the numeric ID or the full ID in the format `folders/{folder_id}`. Only one of `project_id`, `folder_id`, `organization_id`, `bucket_name`, `service_account_email`, or `pubsub_topic_id` must be specified.
      type: string
      required: false
      default: null
    - name: mode
      description: "Mode of operation. 'authoritative' creates 'google_*_iam_binding' resources, overwriting any existing members for the given roles. Warning: This is a destructive operation and can remove existing IAM members from the specified roles. 'additive' creates 'google_*_iam_member' resources, adding members to roles without affecting existing members."
      type: string
      required: false
      default: "additive"
    - name: organization_id
      description: The numeric ID of the organization (e.g., '123456789012') to apply IAM policies to. Only one of `project_id`, `folder_id`, `organization_id`, `bucket_name`, `service_account_email`, or `pubsub_topic_id` must be specified.
      type: string
      required: false
      default: null
    - name: project_id
      description: The ID of the project to apply IAM policies to. Only one of `project_id`, `folder_id`, `organization_id`, `bucket_name`, `service_account_email`, or `pubsub_topic_id` must be specified.
      type: string
      required: false
      default: null
    - name: pubsub_topic_id
      description: The ID of the Pub/Sub topic to apply IAM policies to, in the format `projects/PROJECT_ID/topics/TOPIC_NAME`. Only one of `project_id`, `folder_id`, `organization_id`, `bucket_name`, `service_account_email`, or `pubsub_topic_id` must be specified.
      type: string
      required: false
      default: null
    - name: service_account_email
      description: The identity of the service account to apply IAM policies to. Can be the short email address, or the full resource name `projects/PROJECT_ID/serviceAccounts/SA_EMAIL`. Only one of `project_id`, `folder_id`, `organization_id`, `bucket_name`, `service_account_email`, or `pubsub_topic_id` must be specified.
      type: string
      required: false
      default: null
  terraformVariableGroups:
    - title: Resource Scope
      description: Specify exactly one resource to apply IAM policies to.
      expanded: true
      variables:
        - project_id
        - folder_id
        - organization_id
        - bucket_name
        - service_account_email
        - pubsub_topic_id
    - title: IAM Configuration
      description: Define the IAM roles, members, and the mode of application.
      expanded: true
      variables:
        - bindings
        - mode
  outputs:
    - name: additive_members
      description: A map of the additive IAM member resources created by this module, keyed by a composite of role and member.
    - name: authoritative_bindings
      description: A map of the authoritative IAM binding resources created by this module, keyed by role.
  requirements:
    services:
      - cloudresourcemanager.googleapis.com
      - iam.googleapis.com
      - storage.googleapis.com
      - pubsub.googleapis.com
    roles:
      - level: project
        role: roles/resourcemanager.projectIamAdmin
      - level: folder
        role: roles/resourcemanager.folderIamAdmin
      - level: organization
        role: roles/resourcemanager.organizationAdmin
      - level: project
        role: roles/storage.admin
      - level: project
        role: roles/iam.serviceAccountAdmin
      - level: project
        role: roles/pubsub.admin
    permissions:
      - resourcemanager.projects.setIamPolicy
      - resourcemanager.folders.setIamPolicy
      - resourcemanager.organizations.setIamPolicy
      - storage.buckets.setIamPolicy
      - iam.serviceAccounts.setIamPolicy
      - pubsub.topics.setIamPolicy
