apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-iam-workforce-pool
  source:
    type: git
    git:
      repo: https://github.com/GoogleCloudPlatform/terraform-google-iam-workforce-pool # Placeholder URL
      dir: /
spec:
  info:
    title: IAM Workforce Identity Pool
    version: 1.0.0
    actuationTool:
      type: Terraform
      version: ">= 1.3.0"
    description:
      tagline: Manages a Google Cloud IAM Workforce Identity Pool and its identity providers.
      detailed: This module handles the creation and configuration of a Workforce Identity Pool, which allows you to manage access for a workforce (e.g., employees) to Google Cloud resources. It supports configuring OIDC and SAML identity providers within the pool.
    labels:
      category: "identity-and-access"
  requirements:
    roles:
      - level: Organization
        roles:
          - roles/iam.workforcePoolAdmin
    services:
      - iam.googleapis.com
  interfaces:
    variables:
      - name: organization_id
        description: The organization ID where the workforce pool will be created. If not provided, no resources will be created.
        type: string
        required: true
        defaultValue: null
      - name: workforce_pool_id
        description: The ID of the workforce pool. It must be a globally unique identifier. If not provided, no resources will be created.
        type: string
        required: true
        defaultValue: null
      - name: workforce_pool_display_name
        description: A user-friendly display name for the workforce pool. If not provided, no resources will be created.
        type: string
        required: true
        defaultValue: null
      - name: workforce_pool_description
        description: A description for the workforce pool.
        type: string
        required: false
        defaultValue: ""
      - name: workforce_pool_disabled
        description: Whether the workforce pool is disabled. You cannot use a disabled pool to exchange tokens.
        type: bool
        required: false
        defaultValue: false
      - name: workforce_pool_session_duration
        description: "The duration that the Google Cloud access tokens, console sign-in sessions, and gcloud sign-in sessions from this pool are valid. Acceptable formats are seconds followed by 's', e.g., '3600s'."
        type: string
        required: false
        defaultValue: "3600s"
      - name: workforce_pool_providers
        description: "A map of workforce identity providers to create. The key of the map is the provider_id. Each provider must have exactly one of 'oidc' or 'saml' configuration block defined."
        type: object
        required: false
        sensitive: true
        defaultValue: {}
    variableGroups:
      - name: workforcePoolSettings
        title: Workforce Pool Configuration
        description: Basic settings for the Workforce Identity Pool.
        variables:
          - organization_id
          - workforce_pool_id
          - workforce_pool_display_name
          - workforce_pool_description
          - workforce_pool_disabled
          - workforce_pool_session_duration
      - name: identityProviders
        title: Workforce Identity Providers
        description: Configuration for external identity providers (OIDC or SAML).
        variables:
          - workforce_pool_providers
    outputs:
      - name: workforce_pool_name
        description: The full resource name of the workforce identity pool.
      - name: workforce_pool_id
        description: The ID of the workforce identity pool.
      - name: workforce_pool_state
        description: The state of the workforce identity pool.
      - name: provider_names
        description: A map of the full resource names of the workforce identity providers, keyed by provider ID.
      - name: provider_ids
        description: A list of the IDs of the created workforce identity providers.
